# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rraumain <rraumain@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/29 08:53:02 by rraumain          #+#    #+#              #
#    Updated: 2024/11/04 08:13:34 by rraumain         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = 		libft.a
CC = 		cc
CFLAGS = 	-Wall -Wextra -Werror

CSRC =		ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c\
			ft_strlen.c ft_memset.c ft_bzero.c ft_memcpy.c ft_memmove.c		\
			ft_strlcpy.c ft_strlcat.c ft_toupper.c ft_tolower.c ft_strchr.c	\
			ft_strrchr.c ft_strncmp.c ft_memchr.c ft_memcmp.c ft_strnstr.c	\
			ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c		\
			ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c ft_striteri.c	\
			ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c

CBONUS =	ft_lstnew_bonus.c ft_lstadd_front_bonus.c ft_lstsize_bonus.c	\
			ft_lstlast_bonus.c ft_lstadd_back_bonus.c ft_lstdelone_bonus.c	\
			ft_lstclear_bonus.c ft_lstiter_bonus.c ft_lstmap_bonus.c

OSRC =		$(CSRC:.c=.o)
OBONUS =	$(CBONUS:.c=.o)

all: $(NAME)
	
$(NAME): $(OSRC)
	$(CC) -c $(CFLAGS) $(CSRC)
	ar -rcs $@ $(OSRC)

bonus:	$(OBONUS)
	$(CC) -c $(CFLAGS) $(CBONUS)
	ar -rcs $(NAME) $(OBONUS)

clean:
	rm -f $(OSRC) $(OBONUS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re